
<html>
<head>
 
    
    
<title>About xkcd Password Generator</title> 
<link rel="stylesheet" href="style2.css">
  
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>

<h1>
    About XKCD Password Generator<br> 
</h1>
<body>
    
    <p style="color: black">What is an XKCD password?</p>
<font size="4" color="gray">XKCD password is based on a webcomic created by Randall Munroe, it illustrates a password generated by random words.
The idea is to combine random words generating a password that has more entropy than usual passwords.
For example, a dictionary word has an entropy of around 65000. If we are to combine multiple words to generate a password the complexity of the password increases, hence, making a stronger password.
If we are to add symbols and numbers we add more complexity to password, hence, password is more difficult for cracking software to guess.<br>  </font>
 <br>
 <p style="color: black">Why to use an XKCD password generator?</p>
 
 <font size="4" color="gray">
 <ul>
     <li>Is easier to remember a sequence of random words than random letters 
     <li>Multiple words add complexity to password
     <li> Multiple symbols add complexity to password
     <li> Multiple numbers add complexity to password
 </ul>
 
  <br>
 <p style="color: black">Example:</p>
 
 <font size="4" color="gray">
 <ul>
     <li>XKCD Password: mark-words-horse-9-!
     <li>Random letter passsord: mwh9!
 </ul>
 <p style="color: black">XKCD password mark-words-horse-9-! is a lot easier to remember than mwh9!</p>
 </font>
 <br>
  <a class="pure-button" href="P2.php">Back</a> 
</body>

</html>